site_name: RflyPilot Doc
site_url: https://rflypilot.github.io/
nav:
    # - 介绍: 
    #     - 简介: introduction/introduction.md
    #     - 软硬件架构:  introduction/sys_overview.md
    - Getting Started:
        - 快速使用: quick_start/env_install.md
    - 基本使用:
        - 硬件连接: Basic/hardware_connection.md
        - MIL\SIH\HIL仿真: Basic/simulation.md
        - 在线示波器: Basic/scope.md
        - RflySim3D显示: Basic/rflysim3d.md
        - 远程控制台: Basic/console.md
        - 日志系统: Basic/logger.md
        - 传感器校准: Basic/calibration.md
        - 在线调参: Basic/paramupdate.md
        - 代码生成与交叉编译: Basic/codegen.md
        - 实飞实验: Basic/experiment.md
        # - Quick Start: Basic/index.md
        # - Configuration: Basic/config.md
        - 模型预测控制应用案例: mpc/mpc_example.md
    - 开发者文档: 
        # - SIH: Sim/SIH.md
        # - HIL: Sim/HIL.md
        # - OFFBOARD: Sim/OFFBOARD.md
        - 软硬件架构: development/sys_overview.md
    - 展望:
        - 下一代RflyPilot: Future/future.md
    - Help:
        - Contribute: others/help.md

theme: 
    name: readthedocs
    # name: mkdocs
    highlightjs: true


# markdown_extensions:
#   - nl2br
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences

# plugins:
#   - search
#   - callouts