site_name: RflyPilot Doc
site_url: https://rflypilot.github.io/
nav:
    - Introduction: index.md
    - Basic Use:
        - Quick Start: Basic/index.md
        - Configuration: Basic/config.md
    - Simulation: 
        - SIH: Sim/SIH.md
        - HIL: Sim/HIL.md
    - Help:
        - Contribute: others/help.md

theme: 
    name: readthedocs
    # name: mkdocs
    highlightjs: true