site_name: RflyPilot Doc
site_url: https://rflypilot.github.io/
nav:
    - 介绍: 
        - 简介: introduction/introduction.md
        - 软硬件架构:  introduction/sys_overview.md
    - 快速使用: quick_start/env_install.md
    - 系统组件/功能: acado/acado.md
    - Basic Use:
        - Quick Start: Basic/index.md
        - Configuration: Basic/config.md
    - Simulation: 
        - SIH: Sim/SIH.md
        - HIL: Sim/HIL.md
        - OFFBOARD: Sim/OFFBOARD.md
    - Help:
        - Contribute: others/help.md

theme: 
    name: readthedocs
    # name: mkdocs
    highlightjs: true