site_name: RflyPilot Doc
site_url: https://rflypilot.github.io/
nav:
    - Introduction: 
        - 简介: introduction/introduction.md
        - 系统拓扑:  introduction/sys_overview.md
    - Quick Start:
        - 环境配置: quick_start/env_install.md
        - RflyPilot 安装: quick_start/rflypilot_install.md
        - 快速上手: quick_start/quick_start.md
    - Basic Use:
        - Quick Start: Basic/index.md
        - Configuration: Basic/config.md
    - Simulation: 
        - SIH: Sim/SIH.md
        - HIL: Sim/HIL.md
        - OFFBOARD: Sim/OFFBOARD.md
    - Help:
        - Contribute: others/help.md

theme: 
    name: readthedocs
    # name: mkdocs
    highlightjs: true